##type: SMPModelUpsampleBy2
#type: SMPModel
#kwargs:
#    version: "Unet"
#    encoder_name: "resnet50"
#    encoder_weights: "imagenet"
#    in_channels: ${dataset.kwargs.n_take_channels}
#    classes: ${dataset.kwargs.n_take_channels}


type: SMPModel
kwargs:
    version: "UnetPlusPlus"
    decoder_attention_type: "scse"
    encoder_name: "efficientnet-b3"
    encoder_weights: "imagenet"
    in_channels: ${dataset.kwargs.n_take_channels}
    classes: ${dataset.kwargs.n_take_channels}
