type: SMPModel
kwargs:
    version: "Unet"
    encoder_name: "resnet50"
    encoder_weights: "imagenet"
    in_channels: ${dataset.kwargs.n_appereant_channels}
    classes: ${dataset.kwargs.n_appereant_channels}
