type: SMPModelUpsampleBy2
kwargs:
    version: "Unet"
    encoder_name: "se_resnext101_32x4d"
    encoder_weights: "imagenet"
    in_channels: ${dataset.kwargs.n_take_channels}
    classes: ${dataset.kwargs.n_take_channels}
    decoder_use_batchnorm: "inplace"
