# @package _global_

model:
  type: WrappedUNet2D
  kwargs:
    in_channels: 1
    out_channels: 1
    pretrained: null
    num_groups: 8
    f_maps: 32
    final_sigmoid: false
    is_segmentation: false

dataset:
  kwargs:
    n_take_channels: 1
