type: WrappedUNet3D
kwargs:
  version: UNet3D
  in_channels: 1
  out_channels: 1
#  pretrained: "unet3d.pytorch"
  num_groups: 8
  f_maps: 64
  final_sigmoid: false
  is_segmentation: false
  is3d: true
#  upsample: "deconv"