_version: 2
defaults: []
#  - searcher: default
#  - callbacks: default
#  - semantic_segmentation_model: default
#  - data: default
#  - trainer: default
#  - logger: default
#  - hydra: default

callbacks:
  - _target_: autoalbument.callbacks.MonitorAverageParameterChange
  - _target_: autoalbument.callbacks.SavePolicy
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_last: true
    dirpath: checkpoints

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: auto_alb
  name: aa_${now:%H-%M-%S}

task: classification # Deep learning task. Should either be `classification` or `semantic_segmentation`.
#task: semantic_segmentation # Deep learning task. Should either be `classification` or `semantic_segmentation`.

policy_model:
  task_factor: 0.1
  gp_factor: 10
  temperature: 0.05
  num_sub_policies: 100
  num_chunks: 8
  operation_count: 4

  operations:
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB
      shift_r: true
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB
      shift_g: true
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftRGB
      shift_b: true
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.RandomBrightness
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.RandomContrast
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.Solarize
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.HorizontalFlip
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.VerticalFlip
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.Rotate
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftX
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.ShiftY
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.Scale
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.CutoutFixedNumberOfHoles
    - _target_: autoalbument.faster_autoaugment.models.policy_operations.CutoutFixedSize
    # A list of augmentation operations that will be applied to input data.


classification_model:
  _target_: model.Cifar10ClassificationModel

data:
  dataset:
    _target_: dataset.Cifar10SearchDataset
    root: /home/clay/research/kaggle/sennet/data/cifar10
    train: true
    download: true
  input_dtype: uint8
  preprocessing: null
  normalization:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.247, 0.243, 0.261]

  dataloader:
    _target_: torch.utils.data.DataLoader
    batch_size: 128
    shuffle: true
    num_workers: 8
    pin_memory: true
    drop_last: true

optim:
  main:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0, 0.999]

  policy:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [0, 0.999]

seed: 42

hydra: {}
#  run:
#    dir: /home/clay/research/kaggle/sennet/data_dumps/auto_alb_results/${now:%H-%M-%S}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  benchmark: true
  max_epochs: 40

searcher:
  _target_: autoalbument.faster_autoaugment.search.FasterAutoAugmentSearcher
