predictors:
  threshold: 0.03
  percentile_threshold: null
  dust_threshold: null
#  substride: 0.25
  substride: 1.0
  cropping_border: 0
  tta_kwargs:
    add_flips: true
#    add_flips: false
  models:
    - SMP_Unet_resnext50_32x4d_imagenet-c896x1-bs32-abs8-llr-4-t111-sm0-ema1-cb0-2024-01-12-14-30-28
