predictors:
  threshold: 0.034
  percentile_threshold: null
  dust_threshold: null
#  substride: 0.25
  substride: 0.5
  cropping_border: 0
  tta_kwargs:
    add_flips: true
#    add_flips: false
  models:
    - "SMP_Unet_resnet50_imagenet-c512x8-bs10-abs10-llr-3.5-t111-sm0-ema0-cb0-2024-01-30-00-36-55-single-model"