#post_processing: null
post_processing:
  largest_k: 100
  connectivity: 26

predictors:
  threshold: 0.001
  percentile_threshold: null
  dust_threshold: null
#  substride: 0.25
  substride: 1.0
  cropping_border: 0
  tta_kwargs:
    add_flips: true
#    add_flips: false
  models:
    - "SMP_Unet_resnet50_imagenet-c512x4-bs5-abs5-llr-3.5-t111-sm0-ema0-cb0-2024-02-07-01-34-22-best-model"