predictors:
  threshold: 0.002
  percentile_threshold: null
  dust_threshold: null
#  substride: 0.25
  substride: 
  cropping_border: 0
  tta_kwargs:
    add_flips: true
#    add_flips: false
  models:
    - "SMP3DModelUpsampleBy2_Unet_resnext50_32x4d_imagenet-c512x4-bs6-abs6-llr-3.5-t111-sm0-ema0-cb0-2024-02-01-13-06-40-last-model"