predictors:
  threshold: 0.16
  percentile_threshold: null
  dust_threshold: null
#  substride: 0.25
  substride: 1.0
  cropping_border: 0
  tta_kwargs:
    add_flips: true
#    add_flips: false
  models:
    - "SMP_Unet_resnet50_imagenet-c512x8-bs10-abs10-llr-3-t111-sm0-ema0-cb0-2024-01-24-23-41-08"
    - "SMP_Unet_resnet50_imagenet-c512x1-bs10-abs10-llr-3.5-t111-sm0-ema0-cb0-2024-01-19-18-48-02"
    - "SMP_Unet_resnet101_imagenet-c512x1-bs8-abs8-llr-4-t111-sm0-ema0-cb0-2024-01-16-10-03-23"
    - "SMP(Unet_resnext50_32x4d_imagenet)-c512x1-bs32-llr-3.5-t111-sm0-2024-01-02-04-43-17"
    - "SMP(Unet_resnext50_32x4d_imagenet)-c512x1-bs32-llr-3.5-t111-sm0-2024-01-03-09-57-11"