predictors:
  threshold: 0.01
  dust_threshold: null
  substride: 1.0
#  substride: 1.0
  cropping_border: 0
  tta_kwargs:
    add_flips: true
#    add_flips: false
  models:
    - SMP_Unet_resnet50_imagenet-c512x1-bs16-abs16-llr-4-t111-sm0-ema1-cb0-2024-01-07-12-29-24
