val_check_interval: 500
batch_size: 32
accumulate_grad_batches: 1
num_workers: 8
dry_logger: false
exp_name: three_d_seg
group_name: null # maybe this would be useful for grouping experiments when we do hyperparameter search
patience: 5
max_epochs: 10


model:
  type: UNet3D
  kwargs:
    in_channels: 1
    out_channels: 1
    num_groups: 8
    f_maps: 32
    final_sigmoid: false
    is_segmentation: false
    is3d: true
  load_from_checkpoint: null


optimiser:
  type: "AdamW"
  kwargs:
    lr: 1e-4


train_folders:
  - kidney_1_dense

val_folders:
  - kidney_1_dense
  # - kidney_3_dense


dataset:
  train_substride: 0.25
  val_substride: 1.0
  kwargs:
    crop_size: 64
    n_take_channels: 32
    reduce_zero_label: False
    assert_label_exists: True
    channel_start: 0
    channel_end: null

    crop_size_range: null
    output_crop_size: null
    to_float32: true
    channels_jitter: 0
    p_channel_jitter: 0.0
    load_ann: true
    seg_fill_val: 0
    crop_location_noise: 100

