defaults:
  - _self_
  - model: unet3d
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

val_check_interval: 500
batch_size: 2
apparent_batch_size: 1
num_workers: 16
dry_logger: true
exp_name: three_d_seg
group_name: null # maybe this would be useful for grouping experiments when we do hyperparameter search
patience: 5 # stops if (val_check_interval * patience) steps have passed without improvement in the metric
max_epochs: 100

optimiser:
  type: "AdamW"
  log_lr: -3 # sets lr = 10^{-log_lr}. If ls is not null, then it is used instead of log_lr
  kwargs:
    lr: null

loss:
  - type: BCELoss
    weight: 1.0
#  - type: DiceLoss
#    weight: 1.0
#    kwargs:
#      smooth: 0.0001
#  - type: FocalLoss
#    weight: 1.0
#    kwargs:
#      gamma: 2.0

task:
  kwargs:
    eval_threshold: 0.2

train_folders:
  - kidney_1_dense

val_folders:
#  - kidney_1_dense
   - kidney_3_dense
#   - kidney_3_sparse

dataset:
  train_substride: 0.25
  val_substride: 1.0
  kwargs:
    crop_size: 512
    n_take_channels: 12
    reduce_zero_label: False
    assert_label_exists: True
    channel_start: 0
    channel_end: null
    sample_with_mask: false

    crop_size_range: null
    output_crop_size: null
    to_float32: true
    channels_jitter: 0
    p_channel_jitter: 0.0
    load_ann: true
    seg_fill_val: 0
    crop_location_noise: 0

    # These three allow for rotation and flip augmentation
    add_depth_along_channel: true
    add_depth_along_width: true
    add_depth_along_height: true


    random_crop: true # random_crop augmentation
    random_3d_rotate: true # random_3d_rotate augmentation





hydra:
  sweeper:
    sampler:
      seed: 42
    direction: maximize
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      optimiser.log_lr: range(-4, -3, 1)
