val_check_interval: 1000
#val_check_interval: 50
batch_size: 16
num_workers: 8
dry_logger: false
exp_name: three_d_seg
patience: 5
max_epochs: 10


model:
  type: Resnet3D34
  kwargs:
    in_channels: 1
    out_channels: 1
    num_groups: 8
    f_maps: 32
    final_sigmoid: false
    is_segmentation: false
    is3d: true


optimiser:
  type: "AdamW"
  kwargs:
    lr: 1e-3


train_folders:
  - kidney_1_dense

val_folders:
  - kidney_1_dense
#  - kidney_3_sparse


dataset:
  train_substride: 0.1
  val_substride: 1.0
  kwargs:
    crop_size: 64
    n_take_channels: 64
#    crop_size: 384
#    n_take_channels: 10
    reduce_zero_label: False
    assert_label_exists: True
    channel_start: 0
    channel_end: null

    crop_size_range: null
    output_crop_size: null
    to_float32: true
    channels_jitter: 0
    p_channel_jitter: 0.0
    load_ann: true
    seg_fill_val: 0
    crop_location_noise: 100

